Linking failure on big endian (s390x)
/usr/bin/ld: umac128.o (symbol from plugin): in function `umac_put_u32_le':
(.text+0x0): multiple definition of `umac_put_u32_le'; umac.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status

This function (umac_put_u32_le) has been enclosed in a

 #if (! __LITTLE_ENDIAN__) /* compile time warning thrown otherwise */

block in order to fix this issue for little endian architectures.
Since the function is not used on big endian architectures either,
this can be fixed by changing the above to

 #if 0 /* compile time warning thrown otherwise */